name: SFS Sanity Test 1

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make
    - name: sherryx_sfs
      run: ./sherryx_sfs
    - name: make clean
      run: make clean
